### ISSUE TITLE
Add verbosity option for execution for sp.to.lines

### ISSUE THREAD

**Issue by ghost** [Ramboll/strafica#22]
The sp.to.lines is now always printing out its progress on this and the following lines: https://github.com/Ramboll/strafica/blob/b33e6fe56fa24914142a2761adb4412c214ccb8d/R/sp.R#L171

This makes the progress logs cluttered, when running longer scripts and multi-step data processing pipelines.

While the default option could still be to print out the progress and info, we could provide an option `verbosity=TRUE/FALSE` in the function call to disable logging when needed.

Any thoughts: @mlhollestelle & @ril1 ?

**Comment by mlhollestelle** [comment]
Please go ahead if this makes life easier (I can imagine it does). No objections. 

From a quick glance it would be just:

```
if (verbose) {
        if (progress.due(3, parallel=TRUE))
            progress.eta(time.start, i, length(shapes@lines))
}
```

Agree with roni that input argument with defaults should be `verbose = TRUE`.

For consistency it should also be implemented here:
* [lines.to.sp](https://github.com/Ramboll/strafica/blob/b33e6fe56fa24914142a2761adb4412c214ccb8d/R/sp.R#L62);
* [polys.to.sp](https://github.com/Ramboll/strafica/blob/b33e6fe56fa24914142a2761adb4412c214ccb8d/R/sp.R#L118);
* [sp.to.polys](https://github.com/Ramboll/strafica/blob/b33e6fe56fa24914142a2761adb4412c214ccb8d/R/sp.R#L243).

@rainer-ramboll  would you like to give it a shot? You can follow the [best practice guide](https://github.com/Ramboll/dml-best-practices/blob/master/r-package-development.md).  Happy to help of course.
